### PR TITLE
WIP - Test 18.12

### PR DESCRIPTION
**Pull request by severo**

### CODE REVIEW

**Comment by severo** [comment]
Remaining:

- [ ] add new LDAP objects (ou=pendingusers and ou=pendingorgs)
- [ ] check if https://github.com/georchestra/georchestra/pull/2560 requires a modification in ansible
- [ ] add atlas module?
- [ ] maybe geofence management has changed - to be checked
- [ ] I did not review geoserver nor geonetwork... maybe there are changes

**Comment by severo** [comment]
There is still work to do, feel free to steal it.

**Comment by landryb** [comment]
Thanks for starting it, there's very few chances i'd have time to actually work on it.

One thing to note: if a template config file ends up without `{{ }}` sections after your commits, it means there's nothing to template anymore in that file, and that it can be safely removed from the repo & from the list in https://github.com/georchestra/ansible/blob/master/roles/georchestra/tasks/config.yml#L20 - the default file in the datadir should be fine.

Quickly looking at it, seems it's the case for `geowebcache.properties`, `analytics.properties` & `mapfishapp.properties` - thanks to your work in other PRs moving bits to defaults :)

**Comment by landryb** [comment]
nice, more templates removed - but as is it'll break deployment because https://github.com/georchestra/ansible/blob/master/roles/georchestra/tasks/config.yml#L20 will still look for them.

I like PRs of course, but it's better to know that they've been at least tested ;) Oh well, guess that's for me..

**Comment by severo** [comment]
No no, it's work in progress

**Comment by landryb** [comment]
mostly merged all the bits in the 19.04 branch, thanks ! now testing..

**Pull request closed without merging**
