### PR TITLE
adapt to geOrchestra master / debian stretch

### PR DESCRIPTION
**Pull request by fvanderbiest**
Untested proposal for #48 (playbook applies fine with a recent vagrant 2.x)

### CODE REVIEW

**Comment by fvanderbiest** [comment]
mapfishapp print module fails with
/srv/tomcat/georchestra/webapps/mapfishapp/WEB-INF/print/config.yaml (No such file or directory)

**Comment by fvanderbiest** [comment]
Console is broken
capture du 2017-12-28 14-44-28

**Comment by landryb** [comment]
If by 'console' you mean 'the thing that replaced ldapadmin privateui' then probably, since i've never had the occasion to look at/test it, so it's far from being 'integrated' in this. Probably needs some config files to be templated ? a debian package to install ?

I won't be able to come back to all this before i find the time to update my own georchestra setups, so maybe/hopefully in 2018. In the meantime, do what you'd consider 'sane' :)

**Comment by fvanderbiest** [comment]
Yes, that's it.
Funnlily, view-source:https://georchestra.example.org/ldapadmin/console/ does not even require the angular lib !

**Comment by fvanderbiest** [comment]
> mapfishapp print module fails with
> /srv/tomcat/georchestra/webapps/mapfishapp/WEB-INF/print/config.yaml (No such file or directory)

Fixed with d6bd64c

**Comment by fvanderbiest** [comment]
Console is still unavailable using ansible recipe as of today, message is 
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module admin_console due to:
Error: [$injector:modulerr] Failed to instantiate module angularUtils.directives.dirPagination due to:
Error: [$injector:nomod] Module 'angularUtils.directives.dirPagination' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.0-rc.1/$injector/nomod?p0=angularUtils.directives.dirPagination
    at https://georchestra.example.org/ldapadmin/console/public/libraries.js:3:28733
    at https://georchestra.example.org/ldapadmin/console/public/libraries.js:4:6950
```

**Comment by fvanderbiest** [comment]
Also https://georchestra.example.org/geonetwork/ displays HTTP 500

**Pull request merged**
