### PR TITLE
SSL only

### PR DESCRIPTION
**Pull request by fvanderbiest**
Either this one or https://github.com/landryb/georchestra-ansible/pull/21 should be merged, not both.
... and I prefer this one ;-)

### CODE REVIEW

**Comment by fvanderbiest** [comment]
This will also please @MaxiReglisse , see https://groups.google.com/d/msg/georchestra-dev/Qe100bSUZYs/Hsg5XBp-DwAJ

**Comment by landryb** [comment]
Does a 301 redirect loop here....
```
$curl --insecure -v https://georchestra.demo.craig.fr/ 2>&1|grep Location
< Location: https://georchestra.demo.craig.fr/
```

**Comment by landryb** [comment]
Shouldnt there be a `RewriteCond %{REQUEST_URI} ^/{{ item.dest }}/?.*$` line ?

**Comment by landryb** [comment]
After all thats probably only a local issue.

**Pull request merged**
