### PR TITLE
add ogc-api-records microservice

### PR DESCRIPTION
**Pull request by landryb**
modeled mostly after #90, after discussion in georchestra/datadir#271

cc @fvanderbiest @jahow for comments, @pmauduit for testing :)

### CODE REVIEW

**Review by pmauduit — APPROVED** [review]
LGTM, do you want me to test it into a vagrant box ?

**Comment by pmauduit** [comment]
> cc @fvanderbiest @jahow for comments, @pmauduit for testing :)

tested into a vagrant, gn-ogc-api-records service does not boot at the first time, because it is launched before the objects from GN in database have a chance to have been created:

```
Caused by: org.postgresql.util.PSQLException: ERROR: relation "languages" does not exist
  Position: 146
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553) ~[postgresql-42.2.18.jar!/:42.2.18]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285) ~[postgresql-42.2.18.jar!/:42.2.18]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323) ~[postgresql-42.2.18.jar!/:42.2.18]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473) ~[postgresql-42.2.18.jar!/:42.2.18]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393) ~[postgresql-42.2.18.jar!/:42.2.18]
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164) ~[postgresql-42.2.18.jar!/:42.2.18]
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114) ~[postgresql-42.2.18.jar!/:42.2.18]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-3.4.5.jar!/:na]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.5.jar!/:na]
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57) ~[hibernate-core-5.4.27.Final.jar!/:5.4.27.Final]
        ... 84 common frames omitted
```

But relaunching it by hand afterwards, it works:

Screenshot from 2023-03-30 15-12-25

**Comment by landryb** [comment]
Deployed on https://demo.georchestra.org/ogc-api-records/collections/main/items, ES index still rebuilding but it seems to work fine - besides accents but that... is something to worry about later :)

**Comment by fvanderbiest** [comment]
> accents but that... is something to worry about later :)

We got those damn accents working on geo2france - I'd like we draft a guide on how to correctly configure geonetwork / datahub in French. eg in https://github.com/georchestra/georchestra/tree/master/docs/tutorials to begin with, and most importantly upstream, in the geonetwork documentation.

**Comment by landryb** [comment]
> > accents but that... is something to worry about later :)
> 
> We got those damn accents working on geo2france - I'd like we draft a guide on how to correctly configure geonetwork / datahub in French. eg in https://github.com/georchestra/georchestra/tree/master/docs/tutorials to begin with, and most importantly upstream, in the geonetwork documentation.

fixed by 55f87bc ;)

**Pull request merged**
