### PR TITLE
Update IGN information

### PR DESCRIPTION
**Pull request by pierrejego**
correction to access to htdocs
update IGN url in mapfishapp configuration

I think we should remove sviewer and mapfishapp from playbook .

### CODE REVIEW

**Comment by landryb** [comment]
i dont think the change to [roles/apache/templates/common.conf.j2](https://github.com/georchestra/ansible/pull/104/files#diff-5da643cc4fad9b71bf341cc0b68b45c68af1b9058936e51e3aa6b010fc1f4139) is related ?

**Comment by pierrejego** [comment]
> 

It is.  With those lines you can not access to sviewer, so you can not use the openls service for ign

**Comment by landryb** [comment]
> > 
> 
> It is. With those lines you can not access to sviewer, so you can not use the openls service for ign

i dont understand how those two facts can be related one with each other, care to explain more what is the problem ?

and i'm afraid removing this global / redirect might cause regressions here and there. But i never really understood all this apache config....

**Comment by landryb** [comment]
> I think we should remove sviewer and mapfishapp from playbook .

agreed, i'd rather take a PR achieving this, and properly cleaning up all the remnants :) cf georchestra/georchestra#3661, georchestra/georchestra#3732 and georchestra/georchestra#3815

**Comment by pierrejego** [comment]
for 
```
ProxyPass / http://localhost:{{ tomcat_instances['proxycas']['port'] }}/
ProxyPassReverse / http://localhost:{{ tomcat_instances['proxycas']['port'] }}/
```
You redirect all to security-proxy application

For exemple with some default information from georchestra htdocs, and with those lines uncommented
[](https://gis.jdev.fr/errors/50x.html)
will give
```
Erreur 404
Ressource introuvable.
```
Whereas without those lines 
[](https://gis.jdev.fr/errors/50x.html)
will show you the error page

_i'm afraid removing this global / redirect might cause regressions here and there_

I had always removed thoses lines on all geOrchestra I have deploy to add an index.html page. The only regression is the fact it won't add the end / anymore in url, so you will need to add / manually at the end, or remove all the end / in 
https://github.com/georchestra/ansible/blob/21a643d073b99be1e2bdb39df08b68f7d3e1a4fd/roles/georchestra/templates/security-proxy/targets-mapping.properties.j2#L3

But I agree this change is not directly related to IGN information, it was just for testing sviewer without adding an sviewer.conf apache configuration in /var/www/georchestra/conf . I will uncomment them.

**Pull request merged**
