### PR TITLE
Debian 10

### PR DESCRIPTION
**Pull request by fvanderbiest**
WIP supporting debian 10 (https://github.com/georchestra/georchestra/issues/2688 related), using vagrant + ansible 2.9.2

### CODE REVIEW

**Comment by fvanderbiest** [comment]
`console.properties` being a `latin-1` file ... still an issue with ...
```
TASK [georchestra : template config files] *************************************
changed: [mygeorchestra] => (item={u'file': u'default.properties', u'war': u'.', u'destdir': u''}) => {"ansible_loop_var": "item", "backup_file": "/etc/georchestra/.//default.properties.865.2019-12-10@16:48:29~", "changed": true, "checksum": "1718c6ffb557a8f994387d6012abea5a3be78310", "dest": "/etc/georchestra/.//default.properties", "gid": 0, "group": "root", "item": {"destdir": "", "file": "default.properties", "war": "."}, "md5sum": "0a5859c65e8434bd7cef992a941735c7", "mode": "0644", "owner": "root", "size": 3536, "src": "/home/vagrant/.ansible/tmp/ansible-tmp-1575996509.4-137346579235890/source", "state": "file", "uid": 0}
changed: [mygeorchestra] => (item={u'file': u'targets-mapping.properties', u'war': u'security-proxy', u'destdir': u''}) => {"ansible_loop_var": "item", "backup_file": "/etc/georchestra/security-proxy//targets-mapping.properties.902.2019-12-10@16:48:30~", "changed": true, "checksum": "a2988e502415ef1cead91880ebb3e1b3d7730ed7", "dest": "/etc/georchestra/security-proxy//targets-mapping.properties", "gid": 0, "group": "root", "item": {"destdir": "", "file": "targets-mapping.properties", "war": "security-proxy"}, "md5sum": "d6ab2f75da3a50c5990750059eb28383", "mode": "0644", "owner": "root", "size": 393, "src": "/home/vagrant/.ansible/tmp/ansible-tmp-1575996509.78-248519071242185/source", "state": "file", "uid": 0}
changed: [mygeorchestra] => (item={u'file': u'trusted-users.properties', u'war': u'security-proxy', u'destdir': u''}) => {"ansible_loop_var": "item", "changed": true, "checksum": "9727525c581597c60db566f6254dff5c724d474c", "dest": "/etc/georchestra/security-proxy//trusted-users.properties", "gid": 0, "group": "root", "item": {"destdir": "", "file": "trusted-users.properties", "war": "security-proxy"}, "md5sum": "a70c1b7d263e5a8c53f81be5beda1328", "mode": "0644", "owner": "root", "size": 45, "src": "/home/vagrant/.ansible/tmp/ansible-tmp-1575996510.22-26493669190881/source", "state": "file", "uid": 0}
changed: [mygeorchestra] => (item={u'file': u'log4j.properties', u'war': u'security-proxy', u'destdir': u'log4j'}) => {"ansible_loop_var": "item", "backup_file": "/etc/georchestra/security-proxy/log4j/log4j.properties.972.2019-12-10@16:48:31~", "changed": true, "checksum": "cc391c80da3adc502db754fa8d3f895861ba22a9", "dest": "/etc/georchestra/security-proxy/log4j/log4j.properties", "gid": 0, "group": "root", "item": {"destdir": "log4j", "file": "log4j.properties", "war": "security-proxy"}, "md5sum": "78ca94088b09be9cf2deed0355f2f68a", "mode": "0644", "owner": "root", "size": 1213, "src": "/home/vagrant/.ansible/tmp/ansible-tmp-1575996510.67-168259533105808/source", "state": "file", "uid": 0}
changed: [mygeorchestra] => (item={u'file': u'log4j.xml', u'war': u'cas', u'destdir': u'log4j'}) => {"ansible_loop_var": "item", "backup_file": "/etc/georchestra/cas/log4j/log4j.xml.1009.2019-12-10@16:48:31~", "changed": true, "checksum": "937e9ec69e29a0ed398f44f0ccfac17242df5935", "dest": "/etc/georchestra/cas/log4j/log4j.xml", "gid": 0, "group": "root", "item": {"destdir": "log4j", "file": "log4j.xml", "war": "cas"}, "md5sum": "28a50c8f0d45d2db986f88c9ede24547", "mode": "0644", "owner": "root", "size": 3029, "src": "/home/vagrant/.ansible/tmp/ansible-tmp-1575996511.08-276445732686364/source", "state": "file", "uid": 0}
failed: [mygeorchestra] (item={u'file': u'console.properties', u'war': u'console', u'destdir': u''}) => {"ansible_loop_var": "item", "changed": false, "item": {"destdir": "", "file": "console.properties", "war": "console"}, "msg": "Template source files must be utf-8 encoded"}
...
```

**Comment by landryb** [comment]
myeah i've hit this one too, i think my last commit (https://github.com/georchestra/ansible/commit/69adc225f2c60bbf3d70835c305263b50dd243af#diff-febe3470a651770a594a38e05cb11740R248) messed up the accentued char but github doesnt display it

**Comment by fvanderbiest** [comment]
> Some user bits have `tomcat` while others have `tomcat9` (the tmpfiles thing for example) , are both users existing ?

Nope, only `tomcat` user & group seems to exist ... fixing those bits.

**Comment by fvanderbiest** [comment]
Now I'm worried that tomcat9 pid files do not exist. Seems like others have had the same issue too: https://askubuntu.com/questions/1126108/tomcat-9-doesnt-have-tomcat-pid-file

**Comment by landryb** [comment]
yes we've seen this issue - i dont think we should rely on pidfiles though as it's a mechanism from the past. Maybe a bug in the debian10 tomcat9 package ? cant find any already reported on https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=tomcat9;dist=unstable

**Comment by fvanderbiest** [comment]
> i dont think we should rely on pidfiles though as it's a mechanism from the past

What would you suggest instead ?

**Comment by landryb** [comment]
Ah, now i remember we use our own systemd service file... well IIRC, systemd reads it once it's started (quoting the doc)
```
The service manager will read the PID of the main process of the service from this file after start-up of the service. The service manager will not write to the file configured here, although it will remove the file after the service has shut down if it still exists. The PID file does not need to be owned by a privileged user, but if it is owned by an unprivileged user additional safety restrictions are enforced: the file may not be a symlink to a file owned by a different user (neither directly nor indirectly), and the PID file must refer to a process already belonging to the service.
```
so afaict,setting CATALINA_PID tells the startup/catalina.sh scripts to create the pidfile.

the fix mentioned on askubuntu feels wrong though, but i cant find the corresponding code on the upstream tomcat github repo in https://github.com/apache/tomcat/blame/master/bin/catalina.sh

**Comment by landryb** [comment]
Ah, https://bz.apache.org/bugzilla/show_bug.cgi?id=63041 is the corresponding upstream issue.

**Comment by landryb** [comment]
At that point, i think filing a bug so that debian 10 updates to 9.0.17 (which contains the fix per https://bz.apache.org/bugzilla/show_bug.cgi?id=63041#c30) or backport https://svn.apache.org/viewvc/tomcat/trunk/bin/catalina.sh?r1=1850829&r2=1853508&pathrev=1853508&diff_format=h is the next step.. or patching catalina.sh in the playbook, which is gross. Or maybe dropping `PIDFile` from the `tomcat.service.j2` template and hope that systemd still managers the process fine without that directive.

**Comment by pierrejego** [comment]
Test from debian 9 with Ansible 2.7.5 (python 2.7) to Debian 10 (update on 03/03/2020)

For tomcat9 service problems, I added 

> - name: update tomcat script
>   get_url:
>     url: https://svn.apache.org/viewvc/tomcat/trunk/bin/catalina.sh?revision=1853508&view=co&pathrev=1853508
>     dest: /usr/share/tomcat9/bin/catalina.sh
>     force: true
>     mode: '0755'

in common.yml line 16

geoserver won't start because of 
-XX:+UseParNewGC -XX:ParallelGCThreads=2 \ params in config-geoserver.j2 line 14
since we use now java11 it's not compatible anymore.
I removed those line, there is surely other configuration to adapt.

After that everything was working (I have tested this on a specific branch forked from this branch debian10, but mapfishapp, geonetwork and extractorapp were removed so it did not test them for the moment.)

I can do a PR if you want. I don't know when tomcat9 version will be updated on debian 10.

**Comment by pierrejego** [comment]
For information, yesterday, debian master package were 19.04 not in 20.0.x so installing master with debian 10 will fail on startup because of jdk11 version. I had to download package from buildbot.

**Comment by pmauduit** [comment]
it is possible that the debian package build is broken on Jenkins, we did not take the time to port the debian package generation to github actions. This will be difficult to get out of Jenkins for this job anyway, because of publishing the packages on reprepro on the Paulla servers from github might not be very convenient ...

**Comment by RemiDesgrange** [comment]
@pierrejego  See https://github.com/georchestra/georchestra/issues/2957

**Comment by landryb** [comment]
> Test from debian 9 with Ansible 2.7.5 (python 2.7) to Debian 10 (update on 03/03/2020)
> 
> For tomcat9 service problems, I added
> 
> > * name: update tomcat script
> >   get_url:
> >   url: https://svn.apache.org/viewvc/tomcat/trunk/bin/catalina.sh?revision=1853508&view=co&pathrev=1853508
> >   dest: /usr/share/tomcat9/bin/catalina.sh
> >   force: true
> >   mode: '0755'
> 
> in common.yml line 16
> 
> geoserver won't start because of
> -XX:+UseParNewGC -XX:ParallelGCThreads=2 \ params in config-geoserver.j2 line 14
> since we use now java11 it's not compatible anymore.
> I removed those line, there is surely other configuration to adapt.
> 
> After that everything was working (I have tested this on a specific branch forked from this branch debian10, but mapfishapp, geonetwork and extractorapp were removed so it did not test them for the moment.)
> 
> I can do a PR if you want. I don't know when tomcat9 version will be updated on debian 10.

fixed with 873da795 and edda4de0, thanks @pierrejego ;)

**Pull request merged**
