### PR TITLE
adding the license

### PR DESCRIPTION
**Pull request by fvanderbiest**
After discussion with @landryb --> https://en.wikipedia.org/wiki/ISC_license

### CODE REVIEW

**Comment by fvanderbiest** [comment]
@MaxiReglisse , do you agree with the license ?

**Comment by MaxiReglisse** [comment]
perfect for me.
i didn't see your discussion, but i imagine you are looking for a real public licence, which discharge the authors. an interesting licence would the WTFPL, but it appears to be not very serious, and it is not approuved by the OSI, as described here : https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

**Comment by landryb** [comment]
Fwiw, i also considered the WTFPL, and for me it's a perfectly valid licence, whatever the OSI or the FSF thinks about it. Licences should be readable and understandable by mere mortals :)

**Comment by MaxiReglisse** [comment]
:+1: 
that's why i used LPRAB for geosync. but i don't like "branler", so i wrote "battre".
https://github.com/MaxiReglisse/geosync-ansible/blob/master/licence

**Pull request merged**
